package top.eatup.restaurant.entity;

public class MenuType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_type.id
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_type.name
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu_type.sort
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    private Integer sort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_type.id
     *
     * @return the value of t_menu_type.id
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_type.id
     *
     * @param id the value for t_menu_type.id
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_type.name
     *
     * @return the value of t_menu_type.name
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_type.name
     *
     * @param name the value for t_menu_type.name
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu_type.sort
     *
     * @return the value of t_menu_type.sort
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu_type.sort
     *
     * @param sort the value for t_menu_type.sort
     *
     * @mbg.generated Wed Mar 20 21:25:38 CST 2019
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}