package top.eatup.restaurant.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import top.eatup.restaurant.entity.MenuType;
import top.eatup.restaurant.entity.MenuTypeExample;

public interface MenuTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    long countByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int deleteByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int insert(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int insertSelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    List<MenuType> selectByExample(MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    MenuType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MenuType record, @Param("example") MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MenuType record, @Param("example") MenuTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MenuType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_menu_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MenuType record);
}